<?php
// $Id$
/**
 * @file
 * OpenSourcery base event feature.
 */ 

include_once('os_event.features.inc');

/**
 * Implementation of hook_views_pre_render().
 */
function os_event_views_pre_render(&$view) {
  if ($view->name == 'event_list') {
    // Add css.
    drupal_add_css(drupal_get_path('module', 'os_event') . '/os-event.css');
  }
}

/**
 * Implementations of hook_date_format_types().
 */
function os_event_date_format_types() {
  return array(
    'day' => t('Day'),
    'time' => t('Time'),
  );
}

/**
 * Implementation of hook_date_formats().
 */
function os_event_date_formats() {
  $condensed = array(
    'day' => array(
      'j F Y',
      'l, M j',
      'l, j M',
      'n/j/Y',
    ),
    'time' => array(
      'g:ia',
      'H:i',
    ),
  );
  $formats = array();
  foreach ($condensed as $type => $f) {
    foreach ($f as $format) {
      $formats[] = array(
        'type' => $type,
        'format' => $format,
        'locales' => array(),
      );
    }
  }
  return $formats;
}
